### PR TITLE
Bean on the left, plus on the right

### PR DESCRIPTION
**Pull request by firefish111**
# Hi.
Ok, so, I fixed the image.
After all of that persuasion, here is the image. ~~i'm bad with gimp feel free to improve the image~~

I have added the `png` for it, but I'll give you the `xcf` anyway. You can get the `xcf` [here](https://xcf.firefish.repl.co/beanup.xcf).

### CODE REVIEW

**Comment by firefish111** [comment]
@PolyMarsDev ?

**Comment by firefish111** [comment]
@PolyMarsDev é

**Comment by mandar1jn** [comment]
He never checks github

**Comment by firefish111** [comment]
@mandar1jn rééééééééééééééééééééééé

**Comment by PolyMarsDev** [comment]
As much as I love the bean on the left, plus on the right, I don't think it makes sense to put this in the main branch.

**Pull request closed without merging**
